name: main pipeline

on: [pull_request]

defaults:
  run:
    working-directory: ./codebase/rdicidr-0.1.0

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install dependencies
        run: npm ci
      - name: Archive dependencies
        uses: actions/upload-artifact@v4
        with:
          name: npm-packages
          path: codebase/rdicidr-0.1.0/node_modules
  
  lint:
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Get dependencies
        uses: actions/download-artifact@v4
        with:
          name: npm-packages
      - name: lint
        run: npm run lint
  
  format:
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Get dependencies
        uses: actions/download-artifact@v4
        with:
          name: npm-packages
      - name: format
        run: npm run prettier

  test:
    needs: [install_dependencies]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Get dependencies
        uses: actions/download-artifact@v4
        with:
          name: npm-packages
      - name: test
        run: CI=true npm run test
  
  build:
    needs: [install_dependencies, format]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Get dependencies
        uses: actions/download-artifact@v4
        with:
          name: npm-packages
      - name: build
        run: npm run build